### ISSUE TITLE
other server supports? (BR server)

### ISSUE THREAD

**Issue by Suburbanno** [Aelto/Stava#2]

**Comment by Aelto** [comment]
Stava only works for EUW and NA currently, the other servers should be coming soon.
_It shouldn't be so hard to add them, I just forgot to add them during the development_.
I'll update the issue as it progresses.

**Comment by Aelto** [comment]
Ok, i've added about 9 servers ([link to commit](https://github.com/Aelto/Stava/commit/f22456ab924fd370f842955d74cce874773b9c06)) in the app. You may have to go in the dev branch, [build from the sources](https://github.com/Aelto/Stava#build-from-the-sources) and test the BR server yourself because I don't know any BR account that would be playing.

**Comment by Suburbanno** [comment]
@Aelto I do not know how to do it, I do not mess with this :(

**Comment by Aelto** [comment]
I just tested on a guy in the BR server and it actually worked.
A release with all the servers should be coming soon after the necesarry tests

**Comment by Suburbanno** [comment]
ok, thanks

**Comment by Suburbanno** [comment]
working now, thanks
